# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, OpenGL, QuickCheck }:

cabal.mkDerivation (self: {
  pname = "graphicsFormats";
  version = "0.1";
  sha256 = "0bcqj0n8qqaqfrn21qgkf8si5qgxl3qlsc8djy0rqhnfi2grb8nh";
  buildDepends = [ OpenGL QuickCheck ];
  meta = {
    description = "Classes for renderable objects";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
