# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal }:

cabal.mkDerivation (self: {
  pname = "InfixApplicative";
  version = "1.1";
  sha256 = "03c0jlnlnqm6faiandfg0kzajffk03aazkrqwav3g4vc3cdqwfgp";
  meta = {
    description = "liftA2 for infix operators";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
